//
//  Workspace.swift
//  Config
//
//  Created by 이재훈 on 7/16/25.
//

import ProjectDescription

let workspace = Workspace(
    name: "App Name",
    projects: [
        "Projects/**"
    ],
    generationOptions: .options(enableAutomaticXcodeSchemes: false, autogeneratedWorkspaceSchemes: .disabled)
)

